name: PR

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '3.1.x','5.0.x', '6.0.x' ]
    
    name: Run on dotnet ${{martrix.dotnet}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{martrix.dotnet}}
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --no-restore --verbosity normal