name: Publish to nuget

on:
  release:
    types: [ created, edited ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        dotnet: [ '2.1.x', '3.1.x', '5.0.x' ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }} using dotnet version ${{ matrix.dotnet }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup donet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create the package
        run: dotnet pack --configuration Release -o Release -p:PackageVersion=${GITHUB_REF/refs\/tags\/v/''} --include-source
      - name: Publish the package to NuGet
        env:
          NUGET_AUTH_TOKEN: ${{secrets.PRELUDE_NUGET_AUTH_TOKEN}}
        run: dotnet nuget push Release/*.nupkg --skip-duplicate --no-symbols true --source https://api.nuget.org/v3/index.json -k ${NUGET_AUTH_TOKEN}